FILE FREEFORM = 7E374E25-8E01-4FEE-87F2-390C23C606CD {
	SECTION RAW = sm8150pkg/AcpiTables/Csrt.acpi
	SECTION RAW = sm8150pkg/AcpiTables/DSDT.aml
	SECTION RAW = sm8150pkg/AcpiTables/IORT.aml
	SECTION RAW = sm8150pkg/AcpiTables/Madt.acpi
	SECTION RAW = sm8150pkg/AcpiTables/Pptt.acpi
	SECTION RAW = sm8150pkg/AcpiTables/TPM2.acpi
	SECTION RAW = sm8150pkg/AcpiTables/Facp.acpi
	SECTION RAW = sm8150pkg/AcpiTables/Mcfg.acpi
	SECTION RAW = sm8150pkg/AcpiTables/spcr.acpi
	SECTION RAW = sm8150pkg/AcpiTables/Gtdt.acpi
	SECTION RAW = sm8150pkg/AcpiTables/dbg2.acpi
	SECTION RAW = sm8150pkg/AcpiTables/Facs.acpi
	SECTION UI = "AcpiTables"
  }
