    FILE DRIVER = f541d663-4a48-40aa-aabf-ff158ccae34c {
    SECTION DXE_DEPEX = Dxe/use/SmemDxe/SmemDxe.depex
SECTION PE32 = Dxe/use/SmemDxe/SmemDxe.efi
    SECTION UI = "SmemDxe"
  }




   FILE DRIVER = 10e193df-9966-44e7-b17c-59dd831e20fc {
    SECTION DXE_DEPEX = Dxe/use/ChipInfo/ChipInfo.depex
    SECTION PE32 = Dxe/use/ChipInfo/ChipInfo.efi
    SECTION UI = "ChipInfo"
  }

    FILE DRIVER = B105211B-BBBD-4ADD-A3B0-D1CF4A52154C {
    SECTION DXE_DEPEX = Dxe/use/PlatformInfoDxeDriver/PlatformInfoDxeDriver.depex
    SECTION PE32 = Dxe/use/PlatformInfoDxeDriver/PlatformInfoDxeDriver.efi
    SECTION UI = "PlatformInfoDxeDriver"
  }

    FILE DRIVER = 9A00771F-36D4-4DD5-8916-C48ED9B16B86 {
    SECTION DXE_DEPEX = Dxe/use/HALIOMMU/HALIOMMU.depex
    SECTION PE32 = Dxe/use/HALIOMMU/HALIOMMU.efi
    SECTION UI = "HALIOMMU"
  }

   FILE DRIVER = E43128A8-8692-42B6-8AFA-676158578D18 {
   SECTION DXE_DEPEX = Dxe/use/ULogDxe/ULogDxe.depex
    SECTION PE32 = Dxe/use/ULogDxe/ULogDxe.efi
    SECTION UI = "ULogDxe"
  }

    FILE DRIVER = ABA01FF8-2CCB-4E12-8B2E-CD3F4A742993 {
    SECTION DXE_DEPEX = Dxe/use/CmdDbDxe/CmdDbDxe.depex
    SECTION PE32 = Dxe/use/CmdDbDxe/CmdDbDxe.efi
    SECTION UI = "CmdDbDxe"
  }

    FILE DRIVER = CB29F4D1-7F37-4692-A416-93E82E219711 {
    SECTION DXE_DEPEX = Dxe/use/NpaDxe/NpaDxe.depex
    SECTION PE32 = Dxe/use/NpaDxe/NpaDxe.efi
  SECTION UI = "NpaDxe"
  }

    FILE DRIVER = CB29F4D1-7F37-4692-A416-93E82E219766 {
    SECTION DXE_DEPEX = Dxe/use/RpmhDxe/RpmhDxe.depex
        SECTION PE32 = Dxe/use/RpmhDxe/RpmhDxe.efi
        SECTION UI = "RpmhDxe"
  }

    FILE DRIVER = B43C22DB-6333-490C-872D-0A73439059FD {
    SECTION DXE_DEPEX = Dxe/use/PdcDxe/PdcDxe.depex
        SECTION PE32 = Dxe/use/PdcDxe/PdcDxe.efi
        SECTION UI = "PdcDxe"
  }

    FILE DRIVER = 4DB5DEA6-5302-4D1A-8A82-677A683B0D29 {
    SECTION DXE_DEPEX = Dxe/use/ClockDxe/ClockDxe.depex
        SECTION PE32 = Dxe/use/ClockDxe/ClockDxe.efi
        SECTION UI = "ClockDxe"
  }

    FILE DRIVER = 1B52138D-3FA3-4E50-B958-20887353F809 {
    SECTION DXE_DEPEX = Dxe/use/CPRDxe/CPRDxe.depex
        SECTION PE32 = Dxe/use/CPRDxe/CPRDxe.efi
        SECTION UI = "CPRDxe"
  }

    FILE DRIVER = AF9763A2-033B-4109-8E17-56A98D380C92 {
   SECTION DXE_DEPEX = Dxe/use/DALTLMM/DALTLMM.depex
        SECTION PE32 = Dxe/use/DALTLMM/DALTLMM.efi
        SECTION UI = "DALTLMM"
  }

   FILE DRIVER = 04DE8591-D2B3-4077-BBBE-B12070094EB6 {
    SECTION DXE_DEPEX = Dxe/use/I2C/I2C.depex
        SECTION PE32 = Dxe/use/I2C/I2C.efi
       SECTION UI = "I2C"
  }

    FILE DRIVER = 2a7b4bef-80cd-49e1-b473-374ba4d673fc {
    SECTION DXE_DEPEX = Dxe/use/SPMI/SPMI.depex
    SECTION PE32 = Dxe/use/SPMI/SPMI.efi
    SECTION UI = "SPMI"
  }

   FILE DRIVER = 5776232e-082d-4b75-9a0e-fe1d13f7a5d9 {
   SECTION DXE_DEPEX = Dxe/use/PmicDxe/PmicDxe.depex
    SECTION PE32 = Dxe/use/PmicDxe/PmicDxe.efi
   SECTION UI = "PmicDxe"
  }

 

